CREATE TABLE ai_token_wallets (
    id UUID PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    balance_tokens BIGINT NOT NULL,
    lifetime_purchased_tokens BIGINT NOT NULL,
    lifetime_spent_tokens BIGINT NOT NULL,
    lifetime_refunded_tokens BIGINT NOT NULL,
    free_trial_granted BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_ai_token_wallets_user UNIQUE (user_id),
    CONSTRAINT ck_ai_token_wallet_balance_nonnegative CHECK (balance_tokens >= 0),
    CONSTRAINT ck_ai_token_wallet_purchased_nonnegative CHECK (lifetime_purchased_tokens >= 0),
    CONSTRAINT ck_ai_token_wallet_spent_nonnegative CHECK (lifetime_spent_tokens >= 0),
    CONSTRAINT ck_ai_token_wallet_refunded_nonnegative CHECK (lifetime_refunded_tokens >= 0)
);

CREATE TABLE ai_token_transactions (
    id UUID PRIMARY KEY,
    sequence_number BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    wallet_id UUID NOT NULL,
    transaction_type VARCHAR(32) NOT NULL,
    token_amount BIGINT NOT NULL,
    balance_delta_tokens BIGINT NOT NULL,
    balance_before BIGINT NOT NULL,
    balance_after BIGINT NOT NULL,
    operation_id VARCHAR(255) NOT NULL,
    description VARCHAR(512),
    reference_type VARCHAR(64),
    reference_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_token_transactions_wallet
        FOREIGN KEY (wallet_id) REFERENCES ai_token_wallets (id),
    CONSTRAINT uq_ai_token_transactions_sequence UNIQUE (sequence_number),
    CONSTRAINT uq_ai_token_transactions_operation
        UNIQUE (wallet_id, operation_id, transaction_type),
    CONSTRAINT ck_ai_token_transaction_amount_nonnegative CHECK (token_amount >= 0),
    CONSTRAINT ck_ai_token_transaction_before_nonnegative CHECK (balance_before >= 0),
    CONSTRAINT ck_ai_token_transaction_after_nonnegative CHECK (balance_after >= 0),
    CONSTRAINT ck_ai_token_transaction_delta
        CHECK (balance_after = balance_before + balance_delta_tokens),
    CONSTRAINT ck_ai_token_transaction_type CHECK (
        transaction_type IN (
            'FREE_TRIAL_GRANTED',
            'DEMO_PURCHASE',
            'PURCHASE',
            'SPEND',
            'REFUND',
            'RESERVATION',
            'RESERVATION_RELEASED',
            'ADJUSTMENT'
        )
    )
);

CREATE INDEX idx_ai_token_transactions_user_created
    ON ai_token_transactions (user_id, sequence_number DESC);

CREATE INDEX idx_ai_token_transactions_wallet_sequence
    ON ai_token_transactions (wallet_id, sequence_number);

CREATE INDEX idx_ai_token_transactions_reference
    ON ai_token_transactions (reference_type, reference_id);

CREATE TABLE ai_token_reservations (
    id UUID PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    wallet_id UUID NOT NULL,
    feature VARCHAR(128) NOT NULL,
    reserved_tokens BIGINT NOT NULL,
    committed_tokens BIGINT,
    released_tokens BIGINT,
    status VARCHAR(32) NOT NULL,
    reference_type VARCHAR(64),
    reference_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    committed_at TIMESTAMP WITH TIME ZONE,
    released_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_ai_token_reservations_wallet
        FOREIGN KEY (wallet_id) REFERENCES ai_token_wallets (id),
    CONSTRAINT ck_ai_token_reservation_reserved_positive CHECK (reserved_tokens > 0),
    CONSTRAINT ck_ai_token_reservation_committed_nonnegative
        CHECK (committed_tokens IS NULL OR committed_tokens >= 0),
    CONSTRAINT ck_ai_token_reservation_released_nonnegative
        CHECK (released_tokens IS NULL OR released_tokens >= 0),
    CONSTRAINT ck_ai_token_reservation_status CHECK (
        status IN ('RESERVED', 'COMMITTED', 'RELEASED', 'FAILED')
    )
);

CREATE INDEX idx_ai_token_reservations_user_status
    ON ai_token_reservations (user_id, status);

CREATE INDEX idx_ai_token_reservations_wallet
    ON ai_token_reservations (wallet_id);
