CREATE TABLE document_credit_wallets (
    id UUID PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    balance_credits INTEGER NOT NULL,
    lifetime_purchased_credits INTEGER NOT NULL,
    lifetime_spent_credits INTEGER NOT NULL,
    lifetime_reversed_credits INTEGER NOT NULL,
    free_allowance_granted BOOLEAN NOT NULL,
    migrated_legacy_balance_tokens BIGINT,
    lifecycle_status VARCHAR(32) NOT NULL,
    review_debt_credits INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_document_credit_wallet_owner UNIQUE (user_id),
    CONSTRAINT ck_document_credit_wallet_balance CHECK (balance_credits >= 0),
    CONSTRAINT ck_document_credit_wallet_lifetimes CHECK (
        lifetime_purchased_credits >= 0
        AND lifetime_spent_credits >= 0
        AND lifetime_reversed_credits >= 0
        AND review_debt_credits >= 0
    ),
    CONSTRAINT ck_document_credit_wallet_lifecycle CHECK (
        lifecycle_status IN ('ACTIVE', 'BLOCKED_REVIEW', 'REVOKED')
    )
);

CREATE TABLE document_credit_transactions (
    id UUID PRIMARY KEY,
    sequence_number BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    wallet_id UUID NOT NULL,
    transaction_type VARCHAR(40) NOT NULL,
    document_credits INTEGER NOT NULL,
    balance_delta_credits INTEGER NOT NULL,
    balance_before INTEGER NOT NULL,
    balance_after INTEGER NOT NULL,
    operation_id VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    reference_type VARCHAR(64),
    reference_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_document_credit_transaction_wallet
        FOREIGN KEY (wallet_id) REFERENCES document_credit_wallets (id),
    CONSTRAINT uq_document_credit_transaction_sequence UNIQUE (sequence_number),
    CONSTRAINT uq_document_credit_transaction_operation
        UNIQUE (wallet_id, operation_id, transaction_type),
    CONSTRAINT ck_document_credit_transaction_amount CHECK (document_credits >= 0),
    CONSTRAINT ck_document_credit_transaction_balances CHECK (
        balance_before >= 0
        AND balance_after >= 0
        AND balance_after = balance_before + balance_delta_credits
    ),
    CONSTRAINT ck_document_credit_transaction_type CHECK (
        transaction_type IN (
            'FREE_ALLOWANCE_GRANTED',
            'LEGACY_VALUE_MIGRATED',
            'PURCHASE',
            'PROMOTION_BONUS',
            'DOCUMENT_RESERVED',
            'DOCUMENT_SPENT',
            'DOCUMENT_RESERVATION_RELEASED',
            'REFUND_REVERSAL',
            'DISPUTE_REVERSAL',
            'ADJUSTMENT'
        )
    )
);

CREATE INDEX idx_document_credit_transactions_owner_sequence
    ON document_credit_transactions (user_id, sequence_number DESC);
CREATE INDEX idx_document_credit_transactions_wallet_sequence
    ON document_credit_transactions (wallet_id, sequence_number);

CREATE TABLE document_credit_reservations (
    id UUID PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    wallet_id UUID NOT NULL,
    operation_key VARCHAR(200) NOT NULL,
    document_credits INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    regeneration BOOLEAN NOT NULL,
    reference_type VARCHAR(64),
    reference_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    committed_at TIMESTAMP WITH TIME ZONE,
    released_at TIMESTAMP WITH TIME ZONE,
    last_transition_reason VARCHAR(128) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_document_credit_reservation_wallet
        FOREIGN KEY (wallet_id) REFERENCES document_credit_wallets (id),
    CONSTRAINT uq_document_credit_reservation_operation UNIQUE (user_id, operation_key),
    CONSTRAINT ck_document_credit_reservation_amount CHECK (document_credits BETWEEN 1 AND 2),
    CONSTRAINT ck_document_credit_reservation_status CHECK (
        status IN ('RESERVED', 'COMMITTED', 'RELEASED')
    ),
    CONSTRAINT ck_document_credit_reservation_expiry CHECK (expires_at >= created_at)
);

CREATE INDEX idx_document_credit_reservation_expiry
    ON document_credit_reservations (status, expires_at);

CREATE TABLE payment_orders (
    id UUID PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    status VARCHAR(40) NOT NULL,
    catalog_version VARCHAR(64) NOT NULL,
    pricing_plan_id VARCHAR(64) NOT NULL,
    pricing_plan_name VARCHAR(128) NOT NULL,
    base_document_credits INTEGER NOT NULL,
    promotion_bonus_credits INTEGER NOT NULL,
    price_minor BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    billing_country_intent VARCHAR(2) NOT NULL,
    tax_treatment VARCHAR(32) NOT NULL,
    consumer_terms_version VARCHAR(64) NOT NULL,
    immediate_supply_requested BOOLEAN NOT NULL,
    cancellation_right_loss_acknowledged BOOLEAN NOT NULL,
    consumer_terms_accepted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    stripe_session_id VARCHAR(255),
    stripe_payment_intent_id VARCHAR(255),
    provider_livemode BOOLEAN,
    provider_billing_country VARCHAR(2),
    provider_amount_total_minor BIGINT,
    provider_currency VARCHAR(3),
    reversed_document_credits INTEGER NOT NULL DEFAULT 0,
    review_shortfall_credits INTEGER NOT NULL DEFAULT 0,
    manual_review_reason VARCHAR(128),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    checkout_bound_at TIMESTAMP WITH TIME ZONE,
    paid_at TIMESTAMP WITH TIME ZONE,
    fulfilled_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_payment_order_owner_idempotency UNIQUE (user_id, idempotency_key),
    CONSTRAINT uq_payment_order_stripe_session UNIQUE (stripe_session_id),
    CONSTRAINT uq_payment_order_payment_intent UNIQUE (stripe_payment_intent_id),
    CONSTRAINT ck_payment_order_credits CHECK (
        base_document_credits > 0
        AND promotion_bonus_credits >= 0
        AND reversed_document_credits >= 0
        AND review_shortfall_credits >= 0
    ),
    CONSTRAINT ck_payment_order_price CHECK (price_minor > 0),
    CONSTRAINT ck_payment_order_status CHECK (
        status IN (
            'PENDING_CHECKOUT', 'CHECKOUT_OPEN', 'FULFILLED', 'EXPIRED',
            'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'DISPUTED',
            'MANUAL_REVIEW'
        )
    )
);

CREATE INDEX idx_payment_orders_owner_created ON payment_orders (user_id, created_at DESC);

CREATE TABLE founding_promotion_campaigns (
    id VARCHAR(64) PRIMARY KEY,
    enabled BOOLEAN NOT NULL,
    customer_limit INTEGER NOT NULL,
    active_reservations INTEGER NOT NULL,
    completed_claims INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_founding_campaign_counts CHECK (
        customer_limit >= 0
        AND active_reservations >= 0
        AND completed_claims >= 0
        AND active_reservations + completed_claims <= customer_limit
    )
);

CREATE TABLE founding_promotion_reservations (
    id UUID PRIMARY KEY,
    campaign_id VARCHAR(64) NOT NULL,
    order_id UUID NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    bonus_document_credits INTEGER NOT NULL,
    status VARCHAR(24) NOT NULL,
    completed_owner_key VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    released_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_founding_reservation_campaign
        FOREIGN KEY (campaign_id) REFERENCES founding_promotion_campaigns (id),
    CONSTRAINT fk_founding_reservation_order
        FOREIGN KEY (order_id) REFERENCES payment_orders (id),
    CONSTRAINT uq_founding_reservation_order UNIQUE (order_id),
    CONSTRAINT uq_founding_completed_owner UNIQUE (completed_owner_key),
    CONSTRAINT ck_founding_reservation_bonus CHECK (bonus_document_credits > 0),
    CONSTRAINT ck_founding_reservation_status CHECK (
        status IN ('RESERVED', 'COMPLETED', 'RELEASED')
    )
);

CREATE INDEX idx_founding_reservation_owner_status
    ON founding_promotion_reservations (user_id, status);

CREATE TABLE payment_provider_events (
    id UUID PRIMARY KEY,
    provider VARCHAR(32) NOT NULL,
    provider_event_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    order_id UUID,
    payload_sha256 VARCHAR(64) NOT NULL,
    provider_object_id VARCHAR(255),
    amount_minor BIGINT,
    currency VARCHAR(3),
    billing_country VARCHAR(2),
    provider_livemode BOOLEAN,
    provider_created_at TIMESTAMP WITH TIME ZONE,
    outcome VARCHAR(40) NOT NULL,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_payment_provider_event_order
        FOREIGN KEY (order_id) REFERENCES payment_orders (id),
    CONSTRAINT uq_payment_provider_event UNIQUE (provider, provider_event_id)
);

-- Preserve every remaining legacy unit. A partial 10,000-unit block becomes a
-- whole migrated credit; the ratio is never used for new purchases or spends.
INSERT INTO document_credit_wallets (
    id, user_id, balance_credits, lifetime_purchased_credits,
    lifetime_spent_credits, lifetime_reversed_credits,
    free_allowance_granted, migrated_legacy_balance_tokens,
    lifecycle_status, review_debt_credits, version, created_at, updated_at
)
SELECT id, user_id,
       CASE WHEN balance_tokens = 0 THEN 0 ELSE CAST((balance_tokens + 9999) / 10000 AS INTEGER) END,
       CASE WHEN lifetime_purchased_tokens = 0 THEN 0 ELSE CAST((lifetime_purchased_tokens + 9999) / 10000 AS INTEGER) END,
       CASE WHEN lifetime_spent_tokens = 0 THEN 0 ELSE CAST((lifetime_spent_tokens + 9999) / 10000 AS INTEGER) END,
       CASE WHEN lifetime_refunded_tokens = 0 THEN 0 ELSE CAST((lifetime_refunded_tokens + 9999) / 10000 AS INTEGER) END,
       free_trial_granted, balance_tokens, 'ACTIVE', 0, 0, created_at, updated_at
FROM ai_token_wallets;

INSERT INTO document_credit_transactions (
    id, user_id, wallet_id, transaction_type, document_credits,
    balance_delta_credits, balance_before, balance_after, operation_id,
    description, reference_type, reference_id, created_at
)
SELECT id, user_id, id, 'LEGACY_VALUE_MIGRATED',
       CASE WHEN balance_tokens = 0 THEN 0 ELSE CAST((balance_tokens + 9999) / 10000 AS INTEGER) END,
       CASE WHEN balance_tokens = 0 THEN 0 ELSE CAST((balance_tokens + 9999) / 10000 AS INTEGER) END,
       0,
       CASE WHEN balance_tokens = 0 THEN 0 ELSE CAST((balance_tokens + 9999) / 10000 AS INTEGER) END,
       'LEGACY_VALUE_MIGRATION:' || id,
       'Existing AI Credit value migrated to document credits',
       'LEGACY_AI_TOKEN_WALLET', CAST(id AS VARCHAR), updated_at
FROM ai_token_wallets;

INSERT INTO founding_promotion_campaigns (
    id, enabled, customer_limit, active_reservations, completed_claims, version, updated_at
) VALUES ('founding-200', TRUE, 200, 0, 0, 0, CURRENT_TIMESTAMP);
